import React, { Fragment } from 'react';

export default () => (
  <Fragment>
    <h1>About</h1>
    <p className="modal-item">
      Harmony of the Spheres is a Newtonian n-body gravity simulator that lets
      you explore and play around with the force of gravity in the context of an
      array of scenarios from our solar system and beyond. You can add planets,
      delete the Sun, change the value of the gravitational constant or simply
      lean back and enjoy the dazzling beauty of the pentagram that the orbit of
      Venus traces when Earth is held fixed at the center of the coordinate
      system, and much, much more. An overview of the main features of Harmony
      of the Spheres is provided below.
    </p>
    <h3 className="modal-item">Scientifically Accurate</h3>
    <p className="modal-item">
      The orbits of all the masses simulated in Harmony of the Spheres are
      generated by solving the gravitational n-body problem step by step, for
      the masses in question, given a set of intitial positions and velocities
      at a given point in time. For all the solar system scenarios, these
      positions and velocities were obtained from NASA JPL's Horizon system. If,
      for example, you increase the mass of Jupiter to that of the Sun, what you
      will see is what would actually happen if, somehow, this were to occur in
      reality.
    </p>
    <h3 className="modal-item">Beautiful Views</h3>
    <p className="modal-item">
      You can watch the scenarios unfold from any mass or position in the
      simulation. You can, for instance, look at Mars from Earth, or set the
      camera position to free and the focus to origo to get a global view of the
      simulation. When the camera position is set to free, you can also set the
      focus to any mass in the simulation, and follow it on its path through our
      beautiful universe, from far away, or up close if you zoom in, and from
      any angle.
    </p>
    <h3 className="modal-item">Rotating Reference Frames</h3>
    <p className="modal-item">
      With the rotating reference frame feature, you can observe the Universe
      unfold from the point of view of any of the masses being simulated. This
      allows you to observe peculiar orbits of celestial objects like Earth's
      quasi moon Cruinthe, but also the aformentioned pentagram that the orbit
      of Venus traces as seen from Earth. The rotating reference frame feature
      also makes it possible to beautifully visualize hierarchical systems like,
      for example, the Sun, Earth and Moon system.
    </p>
    <h3 className="modal-item">Add, Delete or Modify Masses</h3>
    <p className="modal-item">
      You can add masses to any scenario, or delete or modify existing masses.
      Ever wanted to find out what would happen and what it would look like if
      Pluto orbited our Moon? With Harmony of the Spheres you can get an answer
      to this, admittedly, slightly odd question. Want to cause some mayhem?
      Chuck Jupiter into the inner solar system and see how the orbits of the
      inner planets get perturbed.
    </p>
    <h3 className="modal-item">Learn with Wikipedia</h3>
    <p className="modal-item">
      Want to learn more about what you are seeing on your screen? Well, you can
      read the Wikipedia article related to every scenario included in Harmony
      of the Spheres by clicking the Scenario Wiki option in the left sidebar:
      happy reading!
    </p>
  </Fragment>
);
