export const GET_SCENARIO = 'GET_SCENARIO';
export const MODIFY_SCENARIO_PROPERTY = 'MODIFY_SCENARIO_PROPERTY';
export const MODIFY_MASS_PROPERTY = 'MODIFY_MASS_PROPERTY';
export const ADD_MASS = 'ADD_MASS';
export const DELETE_MASS = 'DELETE_MASS';
