import React, { Fragment } from 'react';
export default () => (React.createElement(Fragment, null,
    React.createElement("h1", null, "Credits"),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        "Programming by",
        ' ',
        React.createElement("a", { href: "https://github.com/TheHappyKoala/", target: "blank" }, "Darrell A. Huffman"),
        ' ',
        ", maintainer."),
    React.createElement("p", { className: "modal-item" },
        "\u00BB Development of the Verlet, RKF, PEFRL, and RKN family of integrators by",
        ' ',
        React.createElement("a", { href: "https://hugogranstrom.com/", target: "blank" }, "Hugo Granstr\u00F6m"),
        ", collaborator."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        React.createElement("a", { href: "http://www.feynmanlectures.caltech.edu/I_toc.html", target: "blank" }, "Volume One of the Feynman Lectures on Physics"),
        ' ',
        "helped me wrap my head around the gravitational n-body problem and Newtonian mechanics."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        React.createElement("a", { href: "https://nasa3d.arc.nasa.gov/models", target: "blank" }, "Spacecraft 3D models"),
        ' ',
        "courtesy of NASA."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        React.createElement("a", { href: "https://discourse.threejs.org/t/impact-shock-wave/5988", target: "blank" }, "Impact shockwave shader"),
        ' ',
        "developed by the ever spectacular and gloriously helpful prisoner849."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        "Planet and moon textures courtesy of the talented",
        ' ',
        React.createElement("a", { href: "https://github.com/JohnVV", target: "blank" }, "John Van Vlliet"),
        ' ',
        "and the dazzling",
        ' ',
        React.createElement("a", { href: "https://www.deviantart.com/magentameteorite", target: "blank" }, "MagentaMeteorite (Brie Limburger)"),
        "."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        "Perlin noise for the star shaders by Stefan Gustavsson and Ashima Arts"),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        React.createElement("a", { href: "http://openuniverse.sourceforge.net/", target: "blank" }, "Phobos and Deimos 3D models"),
        ' ',
        "courtesy of Raul Alvarez."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        "State Vectors for solar system bodies were obtained from",
        ' ',
        React.createElement("a", { href: "https://ssd.jpl.nasa.gov/horizons.cgi", target: "blank" }, "NASA JPL"),
        "."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        "The kind folks at",
        ' ',
        React.createElement("a", { href: "https://space.stackexchange.com/", target: "blank" }, "space.stackexchange.com"),
        ' ',
        "and",
        ' ',
        React.createElement("a", { href: "https://scicomp.stackexchange.com/", target: "blank" }, "scicomp.stackexchange.com"),
        ' ',
        "for kindly providing answers and feedback that helped me in the development of this application."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        React.createElement("a", { href: "https://wikipedia.com/", target: "blank" }, "WikiPedia"),
        ' ',
        "and all the awesome people that contribute to it with content and the financial resources that keep it up and running."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        "Mr. Doob and all the other people that created the",
        ' ',
        React.createElement("a", { href: "https://threejs.org/", target: "blank" }, "THREE.js WebGL library"),
        "."),
    React.createElement("p", { className: "modal-item" },
        React.createElement("b", null, "\u00BB "),
        "Last, but not least, I would like to credit the Universe for being awesomely weird and thought provoking!")));
//# sourceMappingURL=Credits.js.map